### ISSUE TITLE
translate not work

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [bruceyboy24804/No-Pollution#4]
`Options.GROUP:PollutionToggles,오염 여부 선택

Options.OPTION:NoisePollution,소음 공해
Options.OPTION_DESCRIPTION:NoisePollution,소음 공해 허용 여부를 정합니다 (체크시 허용 및 바닐라 값)

Options.OPTION:NetPollution,넷 오염
Options.OPTION_DESCRIPTION:NetPollution,넷(도로) 공해 허용 여부를 정합니다 (체크시 허용 및 바닐라 값)

Options.OPTION:GroundPollution,토양 오염
Options.OPTION_DESCRIPTION:GroundPollution,토양 오염 허용 여부를 정합니다 (체크시 허용 및 바닐라 값)

Options.OPTION:BuildingPollution,건물 오염
Options.OPTION_DESCRIPTION:BuildingPollution,건물 오염 허용 여부를 정합니다 (체크시 허용 및 바닐라 값이며 대부분 다른 오염시 필요함)

Options.OPTION:GroundWaterPollution,수질 오염
Options.OPTION_DESCRIPTION:GroundWaterPollution,수질 오염 허용 여부를 정합니다 (체크시 허용 및 바닐라 값)

Options.OPTION:AirPollution,대기 오염
Options.OPTION_DESCRIPTION:AirPollution,대기 오염 허용 여부를 정합니다 (체크시 허용 및 바닐라 값)

Options.OPTION:WaterPipePollution,하수 오염
Options.OPTION_DESCRIPTION:WaterPipePollution,하수 오염 허용 여부를 정합니다 (체크시 허용 및 바닐라 값)`

is not working in game.
check please.

thank you!

**Comment by Twotoolus-FLY-LShst** [comment]
![0001](https://github.com/bruceyboy24804/No-Pollution/assets/23209374/184e01db-dcd6-4c00-8302-b546838a2ce2)

**Comment by bruceyboy24804** [comment]
@Twotoolus-FLY-LShst can you update translations now please

**Comment by bruceyboy24804** [comment]
can you update your translation so it looks like this @Twotoolus-FLY-LShst 

Options.OPTION_DESCRIPTION:NoisePollution,Allow noise pollution or not (checked means pollution is active and when unchecked will remove existing pollution)
Options.OPTION:NetPollution,Net Pollution
Options.OPTION_DESCRIPTION:NetPollution,Allow net (road) pollution not (checked means pollution is active)
Options.OPTION:BuildingPollution,Building Pollution
Options.OPTION_DESCRIPTION:BuildingPollution,Allow buildingadd pollution  (checked means pollution is active, required for most other pollution types)
Options.OPTION:GroundPollution,Ground Pollution
Options.OPTION_DESCRIPTION:GroundPollution,Allow ground pollution or (checked means pollution is active and when unchecked will remove existing pollution)
Options.OPTION:GroundWaterPollution,GroundWater Pollution
Options.OPTION_DESCRIPTION:GroundWaterPollution,Allow water pollution or not (Checked means pollution is active)
Options.OPTION:WaterPipePollution,WaterPipe Pollution
Options.OPTION_DESCRIPTION:WaterPipePollution,Allow waterpipe pollution or not (checked means pollution is active)
Options.OPTION:AirPollution,Air Pollution
Options.OPTION_DESCRIPTION:AirPollution,Allow air pollution or not (checked means pollution is active and when unchecked will remove existing pollution)
Options.GROUP:PollutionSliders,Pollution Sliders
Options.OPTION:NoisePollutionControler,Noise Pollution
Options.OPTION_DESCRIPTION:NoisePollutionControler,Control the % of pollution that is being produced

**Comment by Twotoolus-FLY-LShst** [comment]
https://github.com/bruceyboy24804/No-Pollution/pull/5

done. I hope to work =D
